[package]
name = "textwrap"
version = "0.13.1"
authors = ["Martin Geisler <martin@geisler.net>"]
description = "Powerful library for word wrapping, indenting, and dedenting strings"
documentation = "https://docs.rs/textwrap/"
repository = "https://github.com/mgeisler/textwrap"
readme = "README.md"
keywords = ["text", "formatting", "wrap", "typesetting", "hyphenation"]
categories = ["text-processing", "command-line-interface"]
license = "MIT"
edition = "2018"
exclude = [".github/", ".gitignore", "benches/", "examples/"]

[package.metadata.docs.rs]
all-features = true

[badges]
travis-ci = { repository = "mgeisler/textwrap" }
appveyor = { repository = "mgeisler/textwrap" }
codecov = { repository = "mgeisler/textwrap" }

[[bench]]
name = "linear"
harness = false

[dependencies]
smawk = "0.3"
unicode-width = "0.1"
terminal_size = { version = "0.1", optional = true }
hyphenation = { version = "0.8", optional = true, features = ["embed_en-us"] }

[dev-dependencies]
lipsum = "0.7"
version-sync = "0.9"
criterion = "0.3"

[target.'cfg(unix)'.dev-dependencies]
termion = "1.5"
