name: build

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:

  ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install ${{ matrix.rust }} Rust
        run: rustup default ${{ matrix.rust }}

      - name: Test with default features
        run: cargo test

      - name: Test with all features
        run: cargo test --all-features

  windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test with default features
        run: cargo test

  # This builds examples and benchmarks, which are not covered above.
  build-all:
    name: Build all targets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build all targets
        run: cargo build --all-targets

      - name: Build all targets with all features
        run: cargo build --all-targets --all-features

  build-documentation:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build documentation and check intra-doc links
        env:
          RUSTDOCFLAGS: --deny broken_intra_doc_links
        run: cargo doc --all-features --no-deps
